# Generated by Django 6.0.4 on 2026-05-07 15:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


DEFAULT_CATEGORY_PREFIXES = {
    'Bread': ('BRD', '#f59e0b'),
    'Cakes': ('CKE', '#ec4899'),
    'Pastries': ('PAS', '#8b5cf6'),
    'Cookies': ('COOKIE', '#a16207'),
    'Drinks': ('DRINK', '#0ea5e9'),
    'Custom Orders': ('CUSTOM', '#10b981'),
}


def backfill_product_codes(apps, schema_editor):
    Category = apps.get_model('bakery', 'Category')
    Product = apps.get_model('bakery', 'Product')

    for category in Category.objects.all():
        prefix, color = DEFAULT_CATEGORY_PREFIXES.get(
            category.name,
            (''.join(character for character in category.name.upper() if character.isalnum())[:3] or 'PRD', '#f59e0b'),
        )
        if not category.barcode_prefix:
            category.barcode_prefix = prefix
        if not category.color:
            category.color = color
        category.save(update_fields=['barcode_prefix', 'color'])

    counters = {}
    used_item_ids = set(Product.objects.exclude(item_id__isnull=True).values_list('item_id', flat=True))
    used_barcodes = set(Product.objects.exclude(barcode__isnull=True).values_list('barcode', flat=True))
    for product in Product.objects.select_related('category').order_by('id'):
        prefix = product.category.barcode_prefix or 'PRD'
        counters[prefix] = counters.get(prefix, 0) + 1
        if not product.item_id:
            item_id = f'ITM-{product.id:04d}'
            while item_id in used_item_ids:
                counters[prefix] += 1
                item_id = f'ITM-{product.id:04d}-{counters[prefix]}'
            product.item_id = item_id
            used_item_ids.add(item_id)
        if not product.barcode:
            barcode = f'{prefix}-{counters[prefix]:04d}'
            while barcode in used_barcodes:
                counters[prefix] += 1
                barcode = f'{prefix}-{counters[prefix]:04d}'
            product.barcode = barcode
            used_barcodes.add(barcode)
        if not product.theme_color:
            product.theme_color = product.category.color
        product.save(update_fields=['item_id', 'barcode', 'theme_color'])


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_ingredient_expiration_date_ingredient_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='barcode_prefix',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#f59e0b', max_length=20),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='reason',
            field=models.CharField(blank=True, choices=[('restock', 'Restock'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('returned', 'Returned'), ('sampling', 'Used for sampling'), ('staff_consumption', 'Staff consumption')], max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='item_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='bakery.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='theme_color',
            field=models.CharField(default='#f59e0b', max_length=20),
        ),
        migrations.RunPython(backfill_product_codes, migrations.RunPython.noop),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('senior', 'Senior Citizen'), ('pwd', 'PWD'), ('promo', 'Promo Discount')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_channel',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('online', 'Online')], default='walk_in', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment'), ('void', 'Void')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('maya', 'Maya'), ('card', 'Credit/Debit Card')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('archive', 'Archive'), ('stock', 'Stock'), ('sale', 'Sale'), ('void', 'Void'), ('backup', 'Backup'), ('restore', 'Restore'), ('password', 'Password')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed', 'Failed Login')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'login histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoidedSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voided_sale_items', to='bakery.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voided_items', to='bakery.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=50)),
                ('production_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_produced', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_remaining', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='bakery.product')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-production_date', '-created_at'],
                'unique_together': {('product', 'batch_number')},
            },
        ),
    ]
