# Generated by Django 6.0.4 on 2026-05-26 02:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_remove_ingredients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('claimed', 'Claimed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'created_at'], name='activity_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='activity_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['model_name', 'object_id'], name='activity_object_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['product', 'created_at'], name='inventory_product_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['action', 'created_at'], name='inventory_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['sale', 'created_at'], name='inventory_sale_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['action', 'created_at'], name='login_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'created_at'], name='login_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['username', 'created_at'], name='login_username_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'pickup_date'], name='order_status_pickup_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', 'status'], name='order_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_archived'], name='product_active_archive_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['expiry_date'], name='product_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='product_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='product_category_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['product', 'expiry_date', 'production_date'], name='batch_fifo_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['product', 'quantity_remaining'], name='batch_product_remaining_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['expiry_date'], name='batch_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_at'], name='sale_sold_at_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'sold_at'], name='sale_status_sold_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_type', 'sold_at'], name='sale_payment_sold_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_channel', 'sold_at'], name='sale_channel_sold_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_total__gte', 0)), name='order_estimated_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_date__gte', models.F('order_date'))), name='order_pickup_not_before_order'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='product_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='product_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='product_low_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_produced__gte', 1)), name='batch_quantity_produced_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__gte', 0)), name='batch_quantity_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__lte', models.F('quantity_produced'))), name='batch_remaining_not_over_produced'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='sale_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='sale_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='sale_tax_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='sale_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='sale_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('payment_amount__gte', 0)), name='sale_payment_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('change_amount__gte', 0)), name='sale_change_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='saleitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='saleitem_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='saleitem_unit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='saleitem_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='voidedsaleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='voided_saleitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='voidedsaleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='voided_saleitem_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='voidedsaleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='voided_saleitem_line_total_non_negative'),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='bakery.productionbatch'),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='bakery.saleitem'),
        ),
        migrations.AddIndex(
            model_name='batchallocation',
            index=models.Index(fields=['batch', 'created_at'], name='allocation_batch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='batchallocation',
            index=models.Index(fields=['sale_item', 'batch'], name='allocation_item_batch_idx'),
        ),
        migrations.AddConstraint(
            model_name='batchallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='allocation_quantity_positive'),
        ),
    ]
