# Generated by Codex on 2026-05-26

from django.db import migrations, models


SALE_TABLE = "bakery_sale"


def _drop_mysql_check(schema_editor, name):
    try:
        schema_editor.execute(f"ALTER TABLE `{SALE_TABLE}` DROP CHECK `{name}`")
    except Exception:
        pass


def apply_sale_constraints(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    for constraint_name in (
        "sale_tax_rate_non_negative",
        "sale_tax_rate_valid",
        "sale_payment_type_valid",
        "sale_channel_valid",
        "sale_discount_type_valid",
        "sale_status_valid",
    ):
        _drop_mysql_check(schema_editor, constraint_name)

    schema_editor.execute(
        "ALTER TABLE `bakery_sale` "
        "ADD CONSTRAINT `sale_tax_rate_valid` CHECK (`tax_rate` >= 0 AND `tax_rate` <= 1)"
    )
    schema_editor.execute(
        "ALTER TABLE `bakery_sale` "
        "ADD CONSTRAINT `sale_payment_type_valid` "
        "CHECK (`payment_type` IN ('cash', 'gcash', 'maya', 'card'))"
    )
    schema_editor.execute(
        "ALTER TABLE `bakery_sale` "
        "ADD CONSTRAINT `sale_channel_valid` CHECK (`sale_channel` IN ('walk_in', 'online'))"
    )
    schema_editor.execute(
        "ALTER TABLE `bakery_sale` "
        "ADD CONSTRAINT `sale_discount_type_valid` "
        "CHECK (`discount_type` IN ('none', 'senior', 'pwd', 'promo'))"
    )
    schema_editor.execute(
        "ALTER TABLE `bakery_sale` "
        "ADD CONSTRAINT `sale_status_valid` CHECK (`status` IN ('completed', 'voided'))"
    )


def reverse_sale_constraints(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    for constraint_name in (
        "sale_tax_rate_valid",
        "sale_payment_type_valid",
        "sale_channel_valid",
        "sale_discount_type_valid",
        "sale_status_valid",
    ):
        _drop_mysql_check(schema_editor, constraint_name)

    schema_editor.execute(
        "ALTER TABLE `bakery_sale` "
        "ADD CONSTRAINT `sale_tax_rate_non_negative` CHECK (`tax_rate` >= 0)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0008_batchallocation_product_archived_at_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(apply_sale_constraints, reverse_sale_constraints),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="sale",
                    name="sale_tax_rate_non_negative",
                ),
                migrations.AddConstraint(
                    model_name="sale",
                    constraint=models.CheckConstraint(condition=models.Q(tax_rate__gte=0, tax_rate__lte=1), name="sale_tax_rate_valid"),
                ),
                migrations.AddConstraint(
                    model_name="sale",
                    constraint=models.CheckConstraint(
                        condition=(
                            models.Q(payment_type="cash")
                            | models.Q(payment_type="gcash")
                            | models.Q(payment_type="maya")
                            | models.Q(payment_type="card")
                        ),
                        name="sale_payment_type_valid",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="sale",
                    constraint=models.CheckConstraint(
                        condition=models.Q(sale_channel="walk_in") | models.Q(sale_channel="online"),
                        name="sale_channel_valid",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="sale",
                    constraint=models.CheckConstraint(
                        condition=(
                            models.Q(discount_type="none")
                            | models.Q(discount_type="senior")
                            | models.Q(discount_type="pwd")
                            | models.Q(discount_type="promo")
                        ),
                        name="sale_discount_type_valid",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="sale",
                    constraint=models.CheckConstraint(
                        condition=models.Q(status="completed") | models.Q(status="voided"),
                        name="sale_status_valid",
                    ),
                ),
            ],
        ),
    ]
